### PR TITLE
add initial sketch of MyModel class

### PR DESCRIPTION
**Pull request by PeterMitrano**

### CODE REVIEW

**Review by bsaund — APPROVED** [review]
Seems like a good start

**Comment by bsaund** [comment]
I'm working on the metrics stuff now, so you can either merge this now or add more to it before the merge.

**Comment by PeterMitrano** [comment]
currently debugging some issues with the train_step, there is some mysterious behavior with gradients

**Comment by PeterMitrano** [comment]
ok I have a solution which seems good for now -- if the performance turns out to be poor (despite my quick test suggesting otherwise) we can revisit this. For now, can I rebase this?

**Comment by bsaund** [comment]
Yep

**Pull request merged**
